apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{},"creationTimestamp":"2017-06-02T10:03:38Z","generation":1,"labels":{"k8s-app":"kube-proxy"},"name":"kube-proxy","namespace":"kube-system","resourceVersion":"190","selfLink":"/apis/extensions/v1beta1/namespaces/kube-system/daemonsets/kube-proxy","uid":"bf69f93a-477a-11e7-a2bb-02420ac00002"},"spec":{"selector":{"matchLabels":{"k8s-app":"kube-proxy"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"k8s-app":"kube-proxy"}},"spec":{"containers":[{"command":["/usr/local/bin/kube-proxy","--kubeconfig=/var/lib/kube-proxy/kubeconfig.conf","--cluster-cidr=10.244.0.0/16","--cluster-cidr=172.17.0.1/16","--masquerade-all","--conntrack-max=0","--conntrack-max-per-core=0"],"image":"mirantis/hypokube:final","imagePullPolicy":"IfNotPresent","name":"kube-proxy","resources":{},"securityContext":{"privileged":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/lib/kube-proxy","name":"kube-proxy"},{"mountPath":"/hyperkube","name":"hyperkube"}]}],"dnsPolicy":"ClusterFirst","hostNetwork":true,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"kube-proxy","serviceAccountName":"kube-proxy","terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master"}],"volumes":[{"configMap":{"defaultMode":420,"name":"kube-proxy"},"name":"kube-proxy"},{"hostPath":{"path":"/k8s/hyperkube"},"name":"hyperkube"}]}},"templateGeneration":1,"updateStrategy":{"type":"OnDelete"}},"status":{"currentNumberScheduled":0,"desiredNumberScheduled":0,"numberMisscheduled":0,"numberReady":0}}
  generation: 2
  labels:
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: kube-proxy
    spec:
      containers:
      - command:
        - /usr/local/bin/kube-proxy
        - --kubeconfig=/var/lib/kube-proxy/kubeconfig.conf
        - --cluster-cidr=10.244.0.0/16
        - --cluster-cidr=172.17.0.1/16
        - --masquerade-all
        - --conntrack-max=0
        - --conntrack-max-per-core=0
        image: mirantis/hypokube:final
        imagePullPolicy: IfNotPresent
        name: kube-proxy
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kube-proxy
          name: kube-proxy
        - mountPath: /hyperkube
          name: hyperkube
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-proxy
      serviceAccountName: kube-proxy
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - configMap:
          defaultMode: 420
          name: kube-proxy
        name: kube-proxy
      - hostPath:
          path: /k8s/hyperkube
        name: hyperkube

---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFM01EWXlNREEwTlRrek4xb1hEVEkzTURZeE9EQTBOVGt6TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTERUCjMyamJmZVZPamZUeUkzWjFXeklQa29JSUdHVElZTU9CTUFqbXE3enJ1d0RaZHJnRFZUR2k1bWVlTnFmcVN1TkkKa0lhdllZWHJ3cWhQVFhoUitjUWdKMUpVemtSekNyKy8zKzdjNi9ud1c2OFpyME41T3RZanRyMXl0cUtGcUNVRgpkRXg5c2dsQy9SRnJ4aGwvcFFxeFdSYVpTendBa2JhMHcvcEhrUC9wK1hQeWVNSDZ3eUp5MHJOWVphQ0NwRzdSCmticUxwWlY3eGhvelpyTWp6cUVkeE5tT1RpZDBWTXUvM3MwTURRTXpBYW1Ccnl3bXVReWRxYm1BQlVtQWZhT3MKbkRheXNiTm03dDFaSlRFS01jTTh6OU9JVzFyUmppalJ0WlNwc0FGZ3ZxdXhoYlc1MnhpUmVMbGJ0em56cGxVaApnR2RSN2kxYUdjUE9BeHo3KzlzQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIbE5zbStrQ3F1ZU13aUR1MTRCVTVXcDhHU00KNXJoNjBiT3BsZzVaSlVMa0toYTdSWHNSQkdZWDRKdFkxUGV3TjdtUW1SMEVJMHdnVC9qTnFGaGc5N3Ezcy9ZYQpsRTBheUtUKzh5N2xwcXVNbXNjSzhkbk41QkVyc01TY1FnUk12Zy92YmhzQVNCeVJNWENwMEx1WUFOMVJJSUFDCk9veklZd2c2M0srcTFaUjlnN2U3WTVYQkJ3bW9ENFRPVDZ1NUg3OGVjVDlibjQ2Q0NCMTBKa1k3OHFsVXp5TU8KTCtjdUM5ZkdqUjdMVHpGUVJDTmw1d05pakgxQUU1THVPNjVMTG43ZHpSYmZyMzNCd0NmNHhhMU5XMmQ0emFmMQp5UWQ5R3hxYVVqNmc1OU1Gb3Y3d1VpeHcremt2NUlSamtnZ2FPeWZBQVIxQzJUNmVNWEs3MG1XWW1tZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  namespace: a3ViZS1zeXN0ZW0=
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExYTjVjM1JsYlNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZqY21WMExtNWhiV1VpT2lKcmRXSmxMWEJ5YjNoNUxYUnZhMlZ1TFhCemJEWnpJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpYSjJhV05sTFdGalkyOTFiblF1Ym1GdFpTSTZJbXQxWW1VdGNISnZlSGtpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1MWFXUWlPaUkyTVRFek16QTRZeTAxTlRjMUxURXhaVGN0T1Raa1l5MHdNalF5TUdGak1EQXdNRElpTENKemRXSWlPaUp6ZVhOMFpXMDZjMlZ5ZG1salpXRmpZMjkxYm5RNmEzVmlaUzF6ZVhOMFpXMDZhM1ZpWlMxd2NtOTRlU0o5LmF0bl93ejZmNjUtT3g1V1c4RlR1M053aGpmdHBWZUdGM2VEV2pTOWZjb3NVbm95QlRpSFY3ekdyMW5PUmxOd256akFQMjNrS0lNLW9OSmtFZUwzV2JUeVFFS3hiSGExcVZWaUFCaWJmRkVSVkFlNUJsMGVXNmJ0ckxqeU5MNGtzdUd2Z3UxeVhKcm04Mlo0WlJncTdTZ2k2TTBzWDN6aTZORFpTTHpfR2RTMU1zcV9xQWVaa3NmZkxoT1huR281dzhkdW93Mnc5Z3VLLXZOUzBNQXQ2cmpxSmdSTm5VZzV3VDF6RWVFM3A5OEhfMWpnSG5vSnZHZjI1cGNGZFZ4LUllQXkyUDk0NGg1SXdYcllhR2Fjd1VwbkRZZlZpZG81b0hreGR4eFlGYTlzVmNELWxhOGpsUFZNM0xVZFdXaEc0bHdpZUlVN2l4S09HbWVjU2ZQUTNXZw==
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: kube-proxy
    kubernetes.io/service-account.uid: 6113308c-5575-11e7-96dc-02420ac00002
  name: kube-proxy-token-psl6s
  namespace: kube-system
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-proxy
  namespace: kube-system
secrets:
- name: kube-proxy-token-psl6s

---
apiVersion: v1
data:
  kubeconfig.conf: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://192.168.1.25:8443
      name: default
    contexts:
    - context:
        cluster: default
        namespace: default
        user: default
      name: default
    current-context: default
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
kind: ConfigMap
metadata:
  labels:
    app: kube-proxy
  name: kube-proxy
  namespace: kube-system

---

